backup.sh
These files should never be empty, so we exit if they are
=> Verify sql files are not empty before uploading/restoring

backup.sh
granting the root user in our AWS Backup account, awsbackup@articulate.com, full control on the backup files uploaded to S3 from our main AWS account which is owned by ops@articulate.com
=> grant awsbackup@articulate.com full control on backup files

backup.sh
=> Update rds_storage_size var

backup.sh
Reverts articulate/datapipeline-scripts#6
=> Revert "Update rds_storage_size var"

backup.sh
This needs some love and cleanup, but its functional!
=> Working copy of mssql compatible backups

backup.sh
Docker removed the latest tag from mssql-server-linux image
need to add 2017-latest tag
=> missed a few more occurrences of mssql-server-linux

backup.sh
dry up the backup script a bit. make it more readable.
added a trap on exit so it cleans up after itself.
added set -euo pipefail to exit on first command error.
=> Backup script cleanup

backup.sh
pipeline stdout seems to only support a certain number of lines so we're reducing the output a bit
=> reduce verbosity of stdout

backup.sh
mssql backup stdout getting cut off before completion
=> reduce stdout a bit so pipeline doesn't cut off

backup.sh
The last time the AO db backup pipeline failed it was due to a login timeout expired error, which seems to have been transient and could have worked if it was tried again.
```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired. Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Timeout error [258]. . Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Unable to complete login process due to delay in prelogin response.
```
Adding the ability to retry failed `sqlcmd` commands within the backup.sh script so it's more resilient to transient type errors like the one noted above.  I've been able to reproduce the errors in a test environment by removing security groups from a test instance with access to RDS instances in our account - watching …
=> add retry with backoff to the backup.sh script

backup.sh
point the MSSQL backup task to the `articulate-backups-temp` bucket for the backup and restore; copy over the dump file to the correct `articulate-db-backups` bucket after the restore task is complete (and after assuming the backup role in backups account) then `rm` from the temp bucket.
=> backup mssql databases to the temp backup bucket

backup.sh
null isn't zero, bailing out early isn't what we wanted. Set things to 0 prior to checking for them being 0..
sheesh.
=> null ain't zero bub

backup.sh
I need some additional logging, this isn't really doing what I'd expect.
Adding some additional details to see if I can debug why this isn't working
=> adding some additional logging to debug with

backup.sh
reverting to put us into a known, and hopefully working state.
=> reverting to unbreak

backup.sh
Adding a conditional check to see if there is a stale instance, and only if there is - calling a function to clean it up.
Added additional echos as well to validate we're doing what I *think* we're doing.
=> adding back improved stale instance handling

backup.sh
Adding the ability to timestamp
Adding "wait for rds instance to delete" check
=> timestamps, wait for rds instance delete

backup.sh
Per @michaelcurran most excellent suggestion, changing to leverage built in CLI wait!
=> leveraging built in wait

backup.sh
We may have to also add the repo to the base image. I did not see it on the machine when I debug'd this.
=> Use new package name for postgres 10 & 11

psql-backups-iam-auth.sh
why do we use `pg_dumpall.sh` let's try removing this
=> update to remove pg_dumpall.sh

backup.sh, psql-backups-iam-auth.sh, psql-backups.sh
While the timestamps in the backup scripts are helpful, the text formatting is a bit hard to read. This should fix that.
Also added a timestamp to the cleanup_on_exit function.
=> Fix hard to read timestamps

backup.sh, psql-backups-iam-auth.sh, psql-backups.sh
Reverts articulate/datapipeline-scripts#65
=> Revert "Remove extra quotation"

backup.sh, psql-backups-iam-auth.sh, psql-backups.sh
Reverts articulate/datapipeline-scripts#64
=> Revert "Updating PG version check"

backup.sh
From thread: https://articulate.slack.com/archives/C01QU7VUS6M/p1615983809021600
=> Fix for "do nothing" error
